engines:
  duplication:
    enabled: true
    config:
      languages:
      - python:
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "mlbgame/*.py"
exclude_paths:
  - "examples/*"
  - "tests/**/*"
