#!/usr/bin/env python2

import mlbgame.update_games
import sys
import getopt

try:
    data = getopt.getopt(sys.argv[1:], "h", ["help", "hide", "box_score", "start_date="])
except getopt.GetoptError:
    mlbgame.update_games.usage()
    sys.exit(2)
hide = False
box_score = False
start_date = 2012
for x in data[0]:
    if x[0] == "-h" or x[0] == "--help":
        mlbgame.update_games.usage()
        sys.exit()
    elif x[0] == "--hide":
        hide = True
    elif x[0] == "--box_score":
        box_score = True
    elif x[0] == "--start_date":
        start_date = int(x[1])
mlbgame.update_games.run(hide, box_score, start_date)